#pragma once

#include <boost/preprocessor/repetition/enum_params.hpp>
#include <boost/preprocessor/repetition/enum_binary_params.hpp>
#include <boost/preprocessor/repetition/repeat_from_to.hpp>
#include <boost/preprocessor/arithmetic/inc.hpp>

#ifndef UTILITY_MAKE_MAX_ARITY
#define UTILITY_MAKE_MAX_ARITY 8
#endif

#ifndef UTILITY_MAKE_AGGR_MAX_ARITY
#define UTILITY_MAKE_AGGR_MAX_ARITY UTILITY_MAKE_MAX_ARITY
#endif

#ifndef UTILITY_MAKE_AGGR_TYPE_MAX_ARITY
#define UTILITY_MAKE_AGGR_TYPE_MAX_ARITY 16
#endif

namespace Utility{

#define UTILITY_MAKE_IMPL_LEVEL0_M2H4U3J9H3IR934YJ5I(Z,NA,NX)															\
	template< template< BOOST_PP_ENUM_PARAMS(NX, class X) > class T, BOOST_PP_ENUM_PARAMS(NA, class A) >				\
	T< BOOST_PP_ENUM_PARAMS(NX,A) > Make( BOOST_PP_ENUM_BINARY_PARAMS( NA, const A, &a ) )								\
	{	return T< BOOST_PP_ENUM_PARAMS(NX,A) >( BOOST_PP_ENUM_PARAMS( NA, a ) );	}

#define UTILITY_MAKE_IMPL_LEVEL1_M54Y24TRW8SS56S7SFHA(Z,N,_)	\
	BOOST_PP_REPEAT_FROM_TO( N, BOOST_PP_INC(UTILITY_MAKE_MAX_ARITY), UTILITY_MAKE_IMPL_LEVEL0_M2H4U3J9H3IR934YJ5I, N )

BOOST_PP_REPEAT_FROM_TO( 1, BOOST_PP_INC(UTILITY_MAKE_MAX_ARITY), UTILITY_MAKE_IMPL_LEVEL1_M54Y24TRW8SS56S7SFHA, _ )

#undef UTILITY_MAKE_IMPL_LEVEL1_M54Y24TRW8SS56S7SFHA

#undef UTILITY_MAKE_IMPL_LEVEL0_M2H4U3J9H3IR934YJ5I


#define UTILITY_MAKE_AGGR_IMPL_LEVEL0_M8GJ394J7S8LPZNMCV(Z,NA,NX)														\
	template< template< BOOST_PP_ENUM_PARAMS(NX, class X) > class T, BOOST_PP_ENUM_PARAMS(NA, class A) >				\
	T< BOOST_PP_ENUM_PARAMS(NX,A) > MakeAggr( BOOST_PP_ENUM_BINARY_PARAMS( NA, const A, &a ) )							\
	{	T< BOOST_PP_ENUM_PARAMS(NX,A) > aggr = { BOOST_PP_ENUM_PARAMS( NA, a ) };	return aggr; }						\
	template< template< BOOST_PP_ENUM_PARAMS(NX, class X) > class T, BOOST_PP_ENUM_PARAMS(NA, class A) >				\
	T< BOOST_PP_ENUM_PARAMS(NX,A) > TieIntoAggr( BOOST_PP_ENUM_BINARY_PARAMS( NA, A, &a ) )								\
	{	T< BOOST_PP_ENUM_PARAMS(NX,A) > aggr = { BOOST_PP_ENUM_PARAMS( NA, a ) };	return aggr; }

#define UTILITY_MAKE_AGGR_IMPL_LEVEL1_LZ0R5SAYQ824252YAE(Z,N,_)	\
	BOOST_PP_REPEAT_FROM_TO( N, BOOST_PP_INC(UTILITY_MAKE_AGGR_MAX_ARITY), UTILITY_MAKE_AGGR_IMPL_LEVEL0_M8GJ394J7S8LPZNMCV, N )

BOOST_PP_REPEAT_FROM_TO( 1, BOOST_PP_INC(UTILITY_MAKE_AGGR_MAX_ARITY), UTILITY_MAKE_AGGR_IMPL_LEVEL1_LZ0R5SAYQ824252YAE, _ )

#undef UTILITY_MAKE_AGGR_IMPL_LEVEL1_LZ0R5SAYQ824252YAE

#undef UTILITY_MAKE_AGGR_IMPL_LEVEL0_M8GJ394J7S8LPZNMCV

#define UTILITY_MAKE_AGGR_TYPE_IMPL_H092GS0S8XCZJMFAG(Z,N,_)		\
	template< class T, BOOST_PP_ENUM_PARAMS(N, class A) >			\
	T MakeAggr( BOOST_PP_ENUM_BINARY_PARAMS( N, A, const &a ) )		\
	{	T aggr = { BOOST_PP_ENUM_PARAMS( N, a ) };	return aggr; }	\
	template< class T, BOOST_PP_ENUM_PARAMS(N, class A) >			\
	T TieIntoAggr( BOOST_PP_ENUM_BINARY_PARAMS( N, A, &a ) )		\
	{	T aggr = { BOOST_PP_ENUM_PARAMS( N, a ) };	return aggr; }

BOOST_PP_REPEAT_FROM_TO( 1, BOOST_PP_INC(UTILITY_MAKE_AGGR_TYPE_MAX_ARITY), UTILITY_MAKE_AGGR_TYPE_IMPL_H092GS0S8XCZJMFAG, _ )

#undef UTILITY_MAKE_AGGR_TYPE_IMPL_H092GS0S8XCZJMFAG

}
